language: go
sudo: false
go:
  - 1.7.5
  - 1.8
  - tip
os:
  - linux
  - osx
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
install:
  - $GOPATH/bin/dep ensure
script:
  - make test
branches:
  only:
    - master
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username b4b4r07 --token $GITHUB_TOKEN --replace $(grep 'Version =' cmd/root.go | sed -E 's/.*"(.+)"$$/\1/') dist/
