
[[dependencies]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[dependencies]]
  branch = "master"
  name = "github.com/b4b4r07/go-colon"

[[dependencies]]
  branch = "master"
  name = "github.com/briandowns/spinner"

[[dependencies]]
  branch = "master"
  name = "github.com/chzyer/readline"

[[dependencies]]
  branch = "master"
  name = "github.com/fatih/color"

[[dependencies]]
  branch = "master"
  name = "github.com/google/go-github"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/oauth2"
